downloadDataset:
  video_url: https://huggingface.co/datasets/friedrichor/MSR-VTT/resolve/main/MSRVTT_Videos.zip
  caption_urls:
    - file_name: train.json
      url: https://huggingface.co/datasets/friedrichor/MSR-VTT/resolve/main/msrvtt_train_9k.json
    - file_name: test.json 
      url: https://huggingface.co/datasets/friedrichor/MSR-VTT/raw/main/msrvtt_test_1k.json
  video_output_path: dataset/MSRVTT/MSRVTT_Videos.zip
  caption_output_dir: dataset/MSRVTT/MSRVTT-captions

unzipDataset:
  zip_path: dataset/MSR-VTT/MSRVTT_Videos.zip
  extract_dir: dataset/MSR-VTT/MSRVTT_Videos

imageExtractionSplit:
  video_source_dir: dataset/MSR-VTT/MSRVTT_Videos/video
  caption_details:
    - file_path: dataset/MSR-VTT/MSRVTT-captions/train.json
      label: train
    - file_path: dataset/MSR-VTT/MSRVTT-captions/test.json
      label: test
  image_destination_dir: dataset/MSR-VTT/MSRVTT-images
  image_format: jpg

augmentation:
  source_destination_dirs:
    - [dataset/MSR-VTT/MSRVTT-images/train, dataset/MSR-VTT/MSRVTT-images/train]
  image_format: jpg

videoEncoding:
  vit_name: "google/vit-base-patch16-224-in21k"
  source_root_dir: dataset/MSR-VTT/MSRVTT-images
  sub_folders: ['train', 'test']
  destination_root_dir: dataset/MSR-VTT/feature_dataset # dataset/feature_dataset
  image_format: jpg

generateDatasetLabel:
  dataset_details:
    - label: train
      source_json_path: dataset/MSR-VTT/MSRVTT-captions/train.json
      video_data_dir: dataset/MSR-VTT/feature_dataset/train # after encodeing/ feature extraction path
    - label: test
      source_json_path: dataset/MSR-VTT/MSRVTT-captions/test.json
      video_data_dir: dataset/MSR-VTT/feature_dataset/test # after encodeing/ feature extraction path
  destination_root_dir: dataset/MSR-VTT/feature_dataset

training:
  vit_name: google/vit-base-patch16-224-in21k
  gpt2_name: gpt2
  train_csv: dataset/MSR-VTT/feature_dataset/train.csv
  val_csv: dataset/MSR-VTT/feature_dataset/val.csv
  checkpoint_dir: dataset/MSR-VTT/results/checkpoints
  checkpoint_best_dir: dataset/MSR-VTT/results/checkpoints/best
  checkpoint_training_dir: dataset/MSR-VTT/results/checkpoints/training

generateCaption:
  vit_name: google/vit-base-patch16-224-in21k
  gpt2_name: gpt2
  checkpoint_path: dataset/MSR-VTT/MSRVTT_checkpoints/train_model
  data_dirs:
    - dataset/MSR-VTT/feature_dataset/val
    - dataset/MSR-VTT/feature_dataset/test
    - dataset/MSR-VTT/feature_dataset/train
  destination_dir: dataset/MSR-VTT/predict


refineGeneratedCaption:
  process_type: cloud # cloud / local
  files_details: # csv file
    - source: dataset/MSR-VTT/predict/test_pred_best.csv
      destination: dataset/MSR-VTT/refine/test_pred_best.csv
    - source: dataset/MSR-VTT/predict/test_pred_train_best_loss_align.csv
      destination: dataset/MSR-VTT/refine/test_pred_train_best_loss_align.csv
    - source: dataset/MSR-VTT/predict/test_pred_train_best_loss_text.csv
      destination: dataset/MSR-VTT/refine/test_pred_train_best_loss_text.csv
    - source: dataset/MSR-VTT/predict/test_pred_train_best_loss.csv
      destination: dataset/MSR-VTT/refine/test_pred_train_best_loss.csv
    - source: dataset/MSR-VTT/predict/test_pred_train_model.csv
      destination: dataset/MSR-VTT/refine/test_pred_train_model.csv
    - source: dataset/MSR-VTT/predict/train_pred_best.csv
      destination: dataset/MSR-VTT/refine/train_pred_best.csv
    - source: dataset/MSR-VTT/predict/train_pred_train_best_loss_align.csv
      destination: dataset/MSR-VTT/refine/train_pred_train_best_loss_align.csv
    - source: dataset/MSR-VTT/predict/train_pred_train_best_loss_text.csv
      destination: dataset/MSR-VTT/refine/train_pred_train_best_loss_text.csv
    - source: dataset/MSR-VTT/predict/train_pred_train_best_loss.csv
      destination: dataset/MSR-VTT/refine/train_pred_train_best_loss.csv
    - source: dataset/MSR-VTT/predict/train_pred_train_model.csv
      destination: dataset/MSR-VTT/refine/train_pred_train_model.csv


evaluation:
  save_path: dataset/MSR-VTT/results/performance.csv
  verbose: true
  files_details:
    # [model_label, dataset_label,model_path, reference_json_path, reference_column, relatum_json_path, relatum_column]
    - ["best" , "test","dataset/MSR-VTT/checkpoints/best", "dataset/MSR-VTT/MSRVTT-captions/test.json", "caption", "dataset/MSR-VTT/refine/test_pred_best.json", "caption"]
    - ["best" , "train","dataset/MSR-VTT/checkpoints/best", "dataset/MSR-VTT/MSRVTT-captions/train.json", "caption", "dataset/MSR-VTT/refine/train_pred_best.json", "caption"]

    # [model_label, dataset_label,model_path, reference_json_path, reference_column, relatum_json_path, relatum_column, ]
    - ["train_best_loss" , "test","dataset/MSR-VTT/checkpoints/train_best_loss", "dataset/MSR-VTT/MSRVTT-captions/test.json", "caption", "dataset/MSR-VTT/refine/test_pred_train_best_loss.json", "caption"]
    - ["train_best_loss" , "train","dataset/MSR-VTT/checkpoints/train_best_loss", "dataset/MSR-VTT/MSRVTT-captions/train.json", "caption", "dataset/MSR-VTT/refine/train_pred_train_best_loss.json", "caption"]

    # [model_label, dataset_label,model_path, reference_json_path, reference_column, relatum_json_path, relatum_column, ]
    - ["train_best_loss_align" , "test","dataset/MSR-VTT/checkpoints/train_best_loss_align", "dataset/MSR-VTT/MSRVTT-captions/test.json", "caption", "dataset/MSR-VTT/refine/test_pred_train_best_loss_align.json", "caption"]
    - ["train_best_loss_align" , "train","dataset/MSR-VTT/checkpoints/train_best_loss_align", "dataset/MSR-VTT/MSRVTT-captions/train.json", "caption", "dataset/MSR-VTT/refine/train_pred_train_best_loss_align.json", "caption"]

    # [model_label, dataset_label,model_path, reference_json_path, reference_column, relatum_json_path, relatum_column, ]
    - ["train_best_loss_text" , "test","dataset/MSR-VTT/checkpoints/train_best_loss_text", "dataset/MSR-VTT/MSRVTT-captions/test.json", "caption", "dataset/MSR-VTT/refine/test_pred_train_best_loss_text.json", "caption"]
    - ["train_best_loss_text" , "train","dataset/MSR-VTT/checkpoints/train_best_loss_text", "dataset/MSR-VTT/MSRVTT-captions/train.json", "caption", "dataset/MSR-VTT/refine/train_pred_train_best_loss_text.json", "caption"]

    # [model_label, dataset_label,model_path, reference_json_path, reference_column, relatum_json_path, relatum_column, ]
    - ["train_model" , "test","dataset/MSR-VTT/checkpoints/train_model", "dataset/MSR-VTT/MSRVTT-captions/test.json", "caption", "dataset/MSR-VTT/refine/test_pred_train_model.json", "caption"]
    - ["train_model" , "train","dataset/MSR-VTT/checkpoints/train_model", "dataset/MSR-VTT/MSRVTT-captions/train.json", "caption", "dataset/MSR-VTT/refine/train_pred_train_model.json", "caption"]



    # [model_label, dataset_label,model_path, reference_json_path, reference_column, relatum_json_path, relatum_column]
    - ["best" , "test","dataset/MSR-VTT/checkpoints/best", "dataset/MSR-VTT/MSRVTT-captions/test.json", "caption", "dataset/MSR-VTT/refine/test_pred_best.json", "refine_caption"]
    - ["best" , "train","dataset/MSR-VTT/checkpoints/best", "dataset/MSR-VTT/MSRVTT-captions/train.json", "caption", "dataset/MSR-VTT/refine/train_pred_best.json", "refine_caption"]

    # [model_label, dataset_label,model_path, reference_json_path, reference_column, relatum_json_path, relatum_column, ]
    - ["train_best_loss" , "test","dataset/MSR-VTT/checkpoints/train_best_loss", "dataset/MSR-VTT/MSRVTT-captions/test.json", "caption", "dataset/MSR-VTT/refine/test_pred_train_best_loss.json", "refine_caption"]
    - ["train_best_loss" , "train","dataset/MSR-VTT/checkpoints/train_best_loss", "dataset/MSR-VTT/MSRVTT-captions/train.json", "caption", "dataset/MSR-VTT/refine/train_pred_train_best_loss.json", "refine_caption"]

    # [model_label, dataset_label,model_path, reference_json_path, reference_column, relatum_json_path, relatum_column, ]
    - ["train_best_loss_align" , "test","dataset/MSR-VTT/checkpoints/train_best_loss_align", "dataset/MSR-VTT/MSRVTT-captions/test.json", "caption", "dataset/MSR-VTT/refine/test_pred_train_best_loss_align.json", "refine_caption"]
    - ["train_best_loss_align" , "train","dataset/MSR-VTT/checkpoints/train_best_loss_align", "dataset/MSR-VTT/MSRVTT-captions/train.json", "caption", "dataset/MSR-VTT/refine/train_pred_train_best_loss_align.json", "refine_caption"]

    # [model_label, dataset_label,model_path, reference_json_path, reference_column, relatum_json_path, relatum_column, ]
    - ["train_best_loss_text" , "test","dataset/MSR-VTT/checkpoints/train_best_loss_text", "dataset/MSR-VTT/MSRVTT-captions/test.json", "caption", "dataset/MSR-VTT/refine/test_pred_train_best_loss_text.json", "refine_caption"]
    - ["train_best_loss_text" , "train","dataset/MSR-VTT/checkpoints/train_best_loss_text", "dataset/MSR-VTT/MSRVTT-captions/train.json", "caption", "dataset/MSR-VTT/refine/train_pred_train_best_loss_text.json", "refine_caption"]

    # [model_label, dataset_label,model_path, reference_json_path, reference_column, relatum_json_path, relatum_column, ]
    - ["train_model" , "test","dataset/MSR-VTT/checkpoints/train_model", "dataset/MSR-VTT/MSRVTT-captions/test.json", "caption", "dataset/MSR-VTT/refine/test_pred_train_model.json", "refine_caption"]
    - ["train_model" , "train","dataset/MSR-VTT/checkpoints/train_model", "dataset/MSR-VTT/MSRVTT-captions/train.json", "caption", "dataset/MSR-VTT/refine/train_pred_train_model.json", "refine_caption"]

plotHistory:
  destination_dir: dataset/MSR-VTT/results/plots
  model_path: dataset/MSR-VTT/MSRVTT_checkpoints/train_model
  history_path: dataset/MSR-VTT/results/history.csv
  vit_name: google/vit-base-patch16-224-in21k
  gpt2_name: gpt2


