downloadDataset:
  video_url: https://www.kaggle.com/api/v1/datasets/download/sarthakjain004/msvd-clips
  caption_urls:
    - file_name: train.json
      url: https://huggingface.co/datasets/friedrichor/MSVD/resolve/main/msvd_train.json?download=true
    - file_name: test.json 
      url: https://huggingface.co/datasets/friedrichor/MSVD/resolve/main/msvd_test.json?download=true
    - file_name: val.json
      url: https://huggingface.co/datasets/friedrichor/MSVD/resolve/main/msvd_val.json?download=true
  video_output_path: dataset/msvd-clips.zip
  caption_output_dir: dataset/msvd-captions

unzipDataset:
  zip_path: dataset/msvd-clips.zip
  extract_dir: dataset/msvd-clips

imageExtractionSplit:
  video_source_dir: dataset/msvd-clips/YouTubeClips
  caption_details:
    - file_path: dataset/msvd-captions/train.json
      label: train
    - file_path: dataset/msvd-captions/test.json
      label: test
    - file_path: dataset/msvd-captions/val.json
      label: val
  image_destination_dir: dataset/msvd-images
  image_format: jpg

augmentation:
  source_destination_dirs:
    - [dataset/msvd-images/train, dataset/msvd-images/train]
  image_format: jpg

videoEncoding:
  vit_name: "google/vit-base-patch16-224-in21k"
  source_root_dir: dataset/msvd-images
  sub_folders: ['train', 'test', 'val']
  destination_root_dir: dataset/feature_ds # dataset/feature_dataset
  image_format: jpg

generateDatasetLabel:
  dataset_details:
    - label: train
      source_json_path: dataset/msvd-captions/train.json
      video_data_dir: dataset/feature_dataset/train # after encodeing/ feature extraction path
    - label: test
      source_json_path: dataset/msvd-captions/test.json
      video_data_dir: dataset/feature_dataset/test # after encodeing/ feature extraction path
    - label: val
      source_json_path: dataset/msvd-captions/val.json
      video_data_dir: dataset/feature_dataset/val # after encodeing/ feature extraction path
  destination_root_dir: dataset/feature_dataset